### ISSUE TITLE
Corsair HS80 MAX WIRELESS support

### ISSUE THREAD

**Issue by Rexarn** [Sapd/HeadsetControl#321]
### Description

Please add this one, i don't wanna download IQue.
I do not know which device id is the "real" one so i pasted in everything it gave me.

### Headset Name

Corsair HS80 MAX WIRELESS

### Device information

<details>
 <summary>Detailed Device Information</summary>

Device Found
  VendorID: 0x1b1c
 ProductID: 0x0a96
  path: \\?\HID#VID_1B1C&PID_0A96&Col01#7&246a0ded&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
  serial_number: 7BD8BF8ABF5ED065
  Manufacturer: Corsair
  Product:      CORSAIR HS80 MAX WIRELESS Gaming Headset
  Interface:    -1
  Usage-Page: 0xff13 Usageid: 0x1

Device Found
  VendorID: 0x1b1c
 ProductID: 0x0a96
  path: \\?\HID#VID_1B1C&PID_0A96&Col02#7&246a0ded&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}
  serial_number: 7BD8BF8ABF5ED065
  Manufacturer: Corsair
  Product:      CORSAIR HS80 MAX WIRELESS Gaming Headset
  Interface:    -1
  Usage-Page: 0xb Usageid: 0x5

Device Found
  VendorID: 0x1b1c
 ProductID: 0x0a96
  path: \\?\HID#VID_1B1C&PID_0A96&Col03#7&246a0ded&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}
  serial_number: 7BD8BF8ABF5ED065
  Manufacturer: Corsair
  Product:      CORSAIR HS80 MAX WIRELESS Gaming Headset
  Interface:    -1
  Usage-Page: 0xff42 Usageid: 0x1

Device Found
  VendorID: 0x1b1c
 ProductID: 0x0a96
  path: \\?\HID#VID_1B1C&PID_0A96&Col04#7&246a0ded&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
  serial_number: 7BD8BF8ABF5ED065
  Manufacturer: Corsair
  Product:      CORSAIR HS80 MAX WIRELESS Gaming Headset
  Interface:    -1
  Usage-Page: 0xff42 Usageid: 0x2

Device Found
  VendorID: 0x1b1c
 ProductID: 0x0a97
  path: \\?\HID#VID_1B1C&PID_0A97&MI_03&Col01#7&2c0f6295&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
  serial_number: B8CE92D9ABAE85DF
  Manufacturer: Corsair
  Product:      CORSAIR HS80 MAX WIRELESS Gaming Receiver
  Interface:    3
  Usage-Page: 0xc Usageid: 0x1

Device Found
  VendorID: 0x1b1c
 ProductID: 0x0a97
  path: \\?\HID#VID_1B1C&PID_0A97&MI_03&Col02#7&2c0f6295&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}
  serial_number: B8CE92D9ABAE85DF
  Manufacturer: Corsair
  Product:      CORSAIR HS80 MAX WIRELESS Gaming Receiver
  Interface:    3
  Usage-Page: 0xff13 Usageid: 0x1

Device Found
  VendorID: 0x1b1c
 ProductID: 0x0a97
  path: \\?\HID#VID_1B1C&PID_0A97&MI_03&Col03#7&2c0f6295&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}
  serial_number: B8CE92D9ABAE85DF
  Manufacturer: Corsair
  Product:      CORSAIR HS80 MAX WIRELESS Gaming Receiver
  Interface:    3
  Usage-Page: 0xb Usageid: 0x5

Device Found
  VendorID: 0x1b1c
 ProductID: 0x0a97
  path: \\?\HID#VID_1B1C&PID_0A97&MI_03&Col04#7&2c0f6295&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
  serial_number: B8CE92D9ABAE85DF
  Manufacturer: Corsair
  Product:      CORSAIR HS80 MAX WIRELESS Gaming Receiver
  Interface:    3
  Usage-Page: 0xff42 Usageid: 0x1

Device Found
  VendorID: 0x1b1c
 ProductID: 0x0a97
  path: \\?\HID#VID_1B1C&PID_0A97&MI_03&Col05#7&2c0f6295&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}
  serial_number: B8CE92D9ABAE85DF
  Manufacturer: Corsair
  Product:      CORSAIR HS80 MAX WIRELESS Gaming Receiver
  Interface:    3
  Usage-Page: 0xff42 Usageid: 0x2

</details>

**Comment by nafg** [comment]
**Update on Corsair HS80 MAX WIRELESS Support** *(Investigation via Claude Code CLI assistant)*

An attempt was made via Claude Code to implement support for the Corsair HS80 MAX WIRELESS but discovered a fundamental compatibility issue that may explain why this device hasn't been added yet.

## Device Details

**Device Tested:**
- **Product ID:** `0x2a0f` (Vendor ID: `0x1b1c`)
- **Product Name:** "CORSAIR HS80 MAX WIRELESS Gaming Receiver"
- **USB Interfaces:**
  - Interface 0-2: Audio (Class 01)
  - Interface 3: Vendor-specific (Class 00, Protocol 0x22) - **NO DRIVER**
- **HID Interfaces:** **NONE** ❌

**Original Issue (#321) Mentioned:**
- **Product IDs:** `0x0a96` (headset), `0x0a97` (receiver)
- **HID Interfaces:** 4-5 HID interfaces ✅

## The Problem

HeadsetControl's architecture relies on `hidapi` for all device communication. The `0x2a0f` device **does not expose any HID interfaces** - it uses a proprietary vendor-specific USB protocol on interface 3. This makes it **architecturally incompatible** with HeadsetControl in its current form.

Adding `0x2a0f` to the existing Corsair device implementation (`corsair_void_rich.hpp`) doesn't work because the device is not enumerated by `hidapi` at all:
```bash
$ ./headsetcontrol --dev -- --list | grep -i corsair
(no results)

$ lsusb | grep Corsair
Bus 001 Device 016: ID 1b1c:2a0f Corsair CORSAIR HS80 MAX WIRELESS Gaming Receiver
```

## Questions

1. **Are `0x2a0f` and `0x0a97` different hardware revisions?** The original issue mentions `0x0a97` as the receiver, but the tested device is `0x2a0f`.

2. **Did Corsair change the receiver hardware?** Perhaps newer HS80 MAX units ship with a different receiver model that dropped HID support in favor of proprietary protocols.

3. **Can anyone with `0x0a96` or `0x0a97` confirm they have HID interfaces?** This would help determine if this is a hardware revision issue.

## Supporting `0x2a0f` Would Require:

- Adding `libusb` support to HeadsetControl (major architectural change)
- Reverse-engineering the vendor protocol via USB packet capture (Windows + iCUE + Wireshark)
- Implementing a new communication backend separate from the existing HID-based system

This is significantly more complex than adding a new HID device.

I have this hardware and may be able to help with USB captures or testing if maintainers are interested in pursuing support.

---

**System Info:**
- Linux (Fedora 43, kernel 6.18.4)
- Device tested: CORSAIR HS80 MAX WIRELESS Gaming Receiver (1b1c:2a0f)
- HeadsetControl: Latest main branch (620e69f)

**Comment by Sapd** [comment]
Yes that was already explained and discussed here: https://github.com/Sapd/HeadsetControl/issues/178#issuecomment-977967263

Its not possible to configure it over HID

**Comment by nafg** [comment]
Oh sorry for the spam then, should I delete the comment?

**Comment by nafg** [comment]
Claude says HS80 MAX is different than HS80 and it couldn't get those solutions to work

**Comment by Sapd** [comment]
No still fine, provides some insights anyways and also summarizes the problem clearly
